# Generated by Django 4.1.3 on 2022-12-03 17:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.FloatField(default=0.0)),
                ('streetName', models.CharField(default='no  street name', max_length=50)),
                ('Postalcode', models.IntegerField(default=0)),
                ('city', models.CharField(default='no  city name', max_length=50)),
            ],
            options={
                'db_table': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=100)),
                ('familyName', models.CharField(default='no family name', max_length=100)),
                ('email', models.EmailField(default='noemail@gmailcom', max_length=50, unique=True)),
                ('photo', models.ImageField(blank=True, max_length=200, null=True, upload_to='photos/profilePictures')),
                ('specialKey', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Admins',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=100)),
                ('familyName', models.CharField(default='no family name', max_length=100)),
                ('email', models.EmailField(default='noemail@gmailcom', max_length=50, unique=True)),
                ('photo', models.ImageField(blank=True, max_length=200, null=True, upload_to='photos/profilePictures')),
                ('jobTitle', models.CharField(default='Unemployed', max_length=100)),
                ('description', models.CharField(default='No description', max_length=100)),
                ('password', models.CharField(default='PasswordDefault', max_length=100)),
                ('statement', models.CharField(default='No statement ', max_length=100)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Volunteering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='no label', max_length=100)),
                ('description', models.CharField(default='no description', max_length=250)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PortfolioBuilder.user')),
            ],
            options={
                'db_table': 'Volunteering',
            },
        ),
        migrations.CreateModel(
            name='Transcripts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Link', models.URLField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PortfolioBuilder.user')),
            ],
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=100)),
                ('familyName', models.CharField(default='no family name', max_length=100)),
                ('PhoneNumber', models.IntegerField(default='no number')),
                ('personaEmail', models.EmailField(default='noemail@gmailcom', max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('senior', 'Senior'), ('junior', 'Junior')], default='junior', max_length=100)),
                ('justification', models.FileField(upload_to='files/justifications')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PortfolioBuilder.user')),
            ],
            options={
                'db_table': 'References',
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNumber', models.IntegerField(default='no number')),
                ('birthDate', models.DateField(default=datetime.date(2003, 1, 1))),
                ('personaEmail', models.EmailField(default='noemail@gmailcom', max_length=50, unique=True)),
                ('personalWebsite', models.URLField()),
                ('linkedinProfile', models.URLField()),
                ('facebookProfile', models.URLField()),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PortfolioBuilder.user')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='PortfolioBuilder.address')),
            ],
        ),
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('senior', 'Senior'), ('junior', 'Junior')], default='junior', max_length=100)),
                ('StartDate', models.DateField(default=datetime.date(2003, 1, 1))),
                ('EndDate', models.DateField(default=datetime.date(2003, 1, 1))),
                ('justification', models.FileField(blank=True, max_length=200, null=True, upload_to='files/justifications')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PortfolioBuilder.user')),
            ],
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('AwardDate', models.DateField(default=datetime.date(2003, 1, 1))),
                ('Justification', models.FileField(blank=True, max_length=200, null=True, upload_to='files/justifications')),
                ('Level', models.CharField(choices=[('High', 'High'), ('Mid', 'Mid'), ('Low', 'Low')], default='Low', max_length=100)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PortfolioBuilder.user')),
            ],
        ),
    ]
